### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by hoangsvit** [GaborTorma/nuxt-dayjs-i18n#9]
I can't install package

![image](https://github.com/user-attachments/assets/c84f7e69-56c8-4176-8f9b-5541ba202108)

**Comment by GaborTorma** [comment]
Solved in the new release

**Comment by hoangsvit** [comment]
it's still not working

```
npm error code 1
npm error path D:\OpenServer\domains\localhost\radio\node_modules\@gabortorma\nuxt-dayjs-i18n
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c pnpm dev:prepare
npm error > @gabortorma/nuxt-dayjs-i18n@5.2.17 dev:prepare D:\OpenServer\domains\localhost\radio\node_modules\@gabortorma\nuxt-dayjs-i18n
npm error > nuxt-module-build build --stub && nuxt-module-build prepare && nuxi prepare playground
npm error
npm error  ERROR  Command failed with exit code 1.
npm error 'nuxt-module-build' is not recognized as an internal or external command,
npm error operable program or batch file.

npm error A complete log of this run can be found in: C:\Users\n.ngoc.minh.hoang\AppData\Local\npm-cache\_logs\2024-09-26T05_35_54_308Z-debug-0.log
```

**Comment by hoangsvit** [comment]
``` shell
pnpm install --shamefully-hoist
  shell: /usr/bin/bash -e {0}
  
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved [3](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:3)1, reused 0, downloaded 16, added 0
Progress: resolved [4](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:4)2, reused 0, downloaded 16, added 0
Progress: resolved 57, reused 0, downloaded 20, added 0
Progress: resolved 1[4](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:5)5, reused 0, downloaded 21, added 0
Progress: resolved 246, reused 0, downloaded 23, added 0
Progress: resolved 340, reused 0, downloaded 2[5](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:6), added 0
Progress: resolved 539, reused 0, downloaded 2[6](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:7), added 0
Progress: resolved 793, reused 0, downloaded 28, added 0
 WARN  [7](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:8) deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@[8](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:9).1.0, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Packages: +782
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 874, reused 0, downloaded 2[9](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:10), added 0
Progress: resolved 874, reused 0, downloaded 34, added 5
Progress: resolved 874, reused 0, downloaded 34, added 28
Progress: resolved 874, reused 0, downloaded 161, added 151
Progress: resolved 874, reused 0, downloaded 345, added 340
Progress: resolved 874, reused 0, downloaded 546, added 531
Progress: resolved 874, reused 0, downloaded 782, added 782, done
.../@gabortorma/nuxt-dayjs-i18n postinstall$ pnpm dev:prepare
.../sharp@0.32.6/node_modules/sharp install$ (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
.../esbuild@0.23.1/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.20.2/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.21.5/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.23.1/node_modules/esbuild postinstall: Done
.../esbuild@0.20.2/node_modules/esbuild postinstall: Done
.../esbuild@0.21.5/node_modules/esbuild postinstall: Done
.../sharp@0.32.6/node_modules/sharp install: sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.[14](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:15).5/libvips-8.14.5-linux-x64.tar.br
.../@gabortorma/nuxt-dayjs-i18n postinstall: > @gabortorma/nuxt-dayjs-i18n@5.2.17 dev:prepare /home/runner/work/radio.eplus.dev/radio.eplus.dev/node_modules/.pnpm/@gabortorma+nuxt-dayjs-i18n@5.2.[17](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:18)_magicast@0.3.5_rollup@4.22.4_vue@3.5.8/node_modules/@gabortorma/nuxt-dayjs-i[18](https://github.com/ePlus-DEV/radio.eplus.dev/actions/runs/11046439018/job/30685769631#step:5:19)n
.../@gabortorma/nuxt-dayjs-i18n postinstall: > nuxt-module-build build --stub && nuxt-module-build prepare && nuxi prepare playground
.../@gabortorma/nuxt-dayjs-i18n postinstall: sh: 1: nuxt-module-build: not found
.../@gabortorma/nuxt-dayjs-i18n postinstall:  ELIFECYCLE  Command failed.
.../@gabortorma/nuxt-dayjs-i18n postinstall:  WARN   Local package.json exists, but node_modules missing, did you mean to install?
.../@gabortorma/nuxt-dayjs-i18n postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by GaborTorma** [comment]
Thanx for reporing. Try the new version.

**Comment by hoangsvit** [comment]
> Thanx for reporing. Try the new version.

Good job, But I have an issue with the setup.

![image](https://github.com/user-attachments/assets/7de18f09-28aa-4619-ab08-71fab520dd43)

Nuxt config

```typescript
[ dayjs: {
    locales: ["vi", "ja", "zh-cn", "zh-tw", "fr", "ru"],
    plugins: ["relativeTime", "utc", "timezone"],
    defaultLocale: "en",
    defaultTimezone: "America/New_York",
  },
  dayjsI18n: {
    computedPlugins: true, // you can specify in array: ['localiztedFormat', 'relativeTime', 'localeData']
    provideFormat: true, // provide $df for Vue
  },
]
```


**Error**

```
 ERROR  Error while requiring module @gabortorma/nuxt-dayjs-i18n: TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute

[13:52:16]  ERROR  Cannot start nuxt:  File URL path must be absolute

  at getPathFromURLWin32 (node:internal/url:1433:11)
  at fileURLToPath (node:internal/url:1464:35)
  at jiti (node_modules\jiti\dist\jiti.js:1:244150)
  at D:/OpenServer/domains/localhost/radio/node_modules/@gabortorma/nuxt-dayjs-i18n/dist/module.mjs:1:199
  at evalModule (node_modules\jiti\dist\jiti.js:1:247313)
  at jiti (node_modules\jiti\dist\jiti.js:1:245241)
  at requireModule (/D:/OpenServer/domains/localhost/radio/node_modules/@nuxt/kit/dist/index.mjs:2243:26)
  at loadNuxtModuleInstance (/D:/OpenServer/domains/localhost/radio/node_modules/@nuxt/kit/dist/index.mjs:2518:92)
  at async installModule (/D:/OpenServer/domains/localhost/radio/node_modules/@nuxt/kit/dist/index.mjs:2470:47)
  at async initNuxt (/D:/OpenServer/domains/localhost/radio/node_modules/nuxt/dist/index.mjs:4506:5)
```
